name: Run Puppeteer Every 5 Minutes and Save Screenshot

on:
  schedule:
    - cron: "*/5 * * * *"  # Menjalankan setiap 5 menit
  workflow_dispatch:  # Memungkinkan Anda menjalankan workflow secara manual

permissions:
  contents: write

jobs:
  puppeteer_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js (latest)
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Initialize Node.js Project
        run: |
          if [ ! -f package.json ]; then
            npm init -y
          fi

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Puppeteer Script
        run: |
          node core.js

      - name: Save Screenshot to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add screenshot.png
          git commit -m "Add screenshot $(date +'%S-%M-%H_%d-%m-%Y')"
          git push || echo "No changes to commit"
